export const CONSTITUENCIES = [
  { id: "1", name: "Manjeshwar", state: "Kerala", district: "Kasaragod" },
  { id: "2", name: "Kasaragod", state: "Kerala", district: "Kasaragod" },
  { id: "3", name: "Udma", state: "Kerala", district: "Kasaragod" },
  { id: "4", name: "Kanhangad", state: "Kerala", district: "Kasaragod" },
  { id: "5", name: "Trikaripur", state: "Kerala", district: "Kasaragod" },
  { id: "6", name: "Payyannur", state: "Kerala", district: "Kannur" },
  { id: "7", name: "Kalliasseri", state: "Kerala", district: "Kannur" },
  { id: "8", name: "Taliparamba", state: "Kerala", district: "Kannur" },
  { id: "9", name: "Irikkur", state: "Kerala", district: "Kannur" },
  { id: "10", name: "Azhikode", state: "Kerala", district: "Kannur" },
  { id: "11", name: "Kannur", state: "Kerala", district: "Kannur" },
  { id: "12", name: "Dharmadam", state: "Kerala", district: "Kannur" },
  { id: "13", name: "Thalassery", state: "Kerala", district: "Kannur" },
  { id: "14", name: "Kuthuparamba", state: "Kerala", district: "Kannur" },
  { id: "15", name: "Mattannur", state: "Kerala", district: "Kannur" },
  { id: "16", name: "Peravoor", state: "Kerala", district: "Kannur" },
  { id: "17", name: "Mananthavady", state: "Kerala", district: "Wayanad" },
  { id: "18", name: "Sulthan Bathery", state: "Kerala", district: "Wayanad" },
  { id: "19", name: "Kalpetta", state: "Kerala", district: "Wayanad" },
  { id: "20", name: "Vadakara", state: "Kerala", district: "Kozhikode" },
  { id: "21", name: "Kuttiadi", state: "Kerala", district: "Kozhikode" },
  { id: "22", name: "Nadapuram", state: "Kerala", district: "Kozhikode" },
  { id: "23", name: "Quilandy", state: "Kerala", district: "Kozhikode" },
  { id: "24", name: "Perambra", state: "Kerala", district: "Kozhikode" },
  { id: "25", name: "Balussery", state: "Kerala", district: "Kozhikode" },
  { id: "26", name: "Elathur", state: "Kerala", district: "Kozhikode" },
  { id: "27", name: "Kozhikode North", state: "Kerala", district: "Kozhikode" },
  { id: "28", name: "Kozhikode South", state: "Kerala", district: "Kozhikode" },
  { id: "29", name: "Beypore", state: "Kerala", district: "Kozhikode" },
  { id: "30", name: "Kunnamangalam", state: "Kerala", district: "Kozhikode" },
  { id: "31", name: "Koduvally", state: "Kerala", district: "Kozhikode" },
  { id: "32", name: "Thiruvambady", state: "Kerala", district: "Kozhikode" },
  { id: "33", name: "Kondotty", state: "Kerala", district: "Malappuram" },
  { id: "34", name: "Eranad", state: "Kerala", district: "Malappuram" },
  { id: "35", name: "Nilambur", state: "Kerala", district: "Malappuram" },
  { id: "36", name: "Wandoor", state: "Kerala", district: "Malappuram" },
  { id: "37", name: "Manjeri", state: "Kerala", district: "Malappuram" },
  { id: "38", name: "Perinthalmanna", state: "Kerala", district: "Malappuram" },
  { id: "39", name: "Mankada", state: "Kerala", district: "Malappuram" },
  { id: "40", name: "Malappuram", state: "Kerala", district: "Malappuram" },
  { id: "41", name: "Vengara", state: "Kerala", district: "Malappuram" },
  { id: "42", name: "Vallikkunnu", state: "Kerala", district: "Malappuram" },
  { id: "43", name: "Tirurangadi", state: "Kerala", district: "Malappuram" },
  { id: "44", name: "Tanur", state: "Kerala", district: "Malappuram" },
  { id: "45", name: "Tirur", state: "Kerala", district: "Malappuram" },
  { id: "46", name: "Kottakkal", state: "Kerala", district: "Malappuram" },
  { id: "47", name: "Thavanur", state: "Kerala", district: "Malappuram" },
  { id: "48", name: "Ponnani", state: "Kerala", district: "Malappuram" },
  { id: "49", name: "Thrithala", state: "Kerala", district: "Palakkad" },
  { id: "50", name: "Pattambi", state: "Kerala", district: "Palakkad" },
  { id: "51", name: "Shornur", state: "Kerala", district: "Palakkad" },
  { id: "52", name: "Ottapalam", state: "Kerala", district: "Palakkad" },
  { id: "53", name: "Kongad", state: "Kerala", district: "Palakkad" },
  { id: "54", name: "Mannarkkad", state: "Kerala", district: "Palakkad" },
  { id: "55", name: "Malampuzha", state: "Kerala", district: "Palakkad" },
  { id: "56", name: "Palakkad", state: "Kerala", district: "Palakkad" },
  { id: "57", name: "Tarur", state: "Kerala", district: "Palakkad" },
  { id: "58", name: "Chittur", state: "Kerala", district: "Palakkad" },
  { id: "59", name: "Nenmara", state: "Kerala", district: "Palakkad" },
  { id: "60", name: "Alathur", state: "Kerala", district: "Palakkad" },
  { id: "61", name: "Chelakkara", state: "Kerala", district: "Thrissur" },
  { id: "62", name: "Kunnamkulam", state: "Kerala", district: "Thrissur" },
  { id: "63", name: "Guruvayur", state: "Kerala", district: "Thrissur" },
  { id: "64", name: "Manalur", state: "Kerala", district: "Thrissur" },
  { id: "65", name: "Wadakkanchery", state: "Kerala", district: "Thrissur" },
  { id: "66", name: "Ollur", state: "Kerala", district: "Thrissur" },
  { id: "67", name: "Thrissur", state: "Kerala", district: "Thrissur" },
  { id: "68", name: "Nattika", state: "Kerala", district: "Thrissur" },
  { id: "69", name: "Kaipamangalam", state: "Kerala", district: "Thrissur" },
  { id: "70", name: "Irinjalakuda", state: "Kerala", district: "Thrissur" },
  { id: "71", name: "Puthukkad", state: "Kerala", district: "Thrissur" },
  { id: "72", name: "Chalakudy", state: "Kerala", district: "Thrissur" },
  { id: "73", name: "Kodungallur", state: "Kerala", district: "Thrissur" },
  { id: "74", name: "Perumbavoor", state: "Kerala", district: "Ernakulam" },
  { id: "75", name: "Angamaly", state: "Kerala", district: "Ernakulam" },
  { id: "76", name: "Aluva", state: "Kerala", district: "Ernakulam" },
  { id: "77", name: "Kalamassery", state: "Kerala", district: "Ernakulam" },
  { id: "78", name: "Paravur", state: "Kerala", district: "Ernakulam" },
  { id: "79", name: "Vypin", state: "Kerala", district: "Ernakulam" },
  { id: "80", name: "Kochi", state: "Kerala", district: "Ernakulam" },
  { id: "81", name: "Thrippunithura", state: "Kerala", district: "Ernakulam" },
  { id: "82", name: "Ernakulam", state: "Kerala", district: "Ernakulam" },
  { id: "83", name: "Thrikkakara", state: "Kerala", district: "Ernakulam" },
  { id: "84", name: "Kunnathunad", state: "Kerala", district: "Ernakulam" },
  { id: "85", name: "Piravom", state: "Kerala", district: "Ernakulam" },
  { id: "86", name: "Muvattupuzha", state: "Kerala", district: "Ernakulam" },
  { id: "87", name: "Kothamangalam", state: "Kerala", district: "Ernakulam" },
  { id: "88", name: "Devikulam", state: "Kerala", district: "Idukki" },
  { id: "89", name: "Udumbanchola", state: "Kerala", district: "Idukki" },
  { id: "90", name: "Thodupuzha", state: "Kerala", district: "Idukki" },
  { id: "91", name: "Idukki", state: "Kerala", district: "Idukki" },
  { id: "92", name: "Peerumade", state: "Kerala", district: "Idukki" },
  { id: "93", name: "Pala", state: "Kerala", district: "Kottayam" },
  { id: "94", name: "Kaduthuruthy", state: "Kerala", district: "Kottayam" },
  { id: "95", name: "Vaikom", state: "Kerala", district: "Kottayam" },
  { id: "96", name: "Ettumanoor", state: "Kerala", district: "Kottayam" },
  { id: "97", name: "Kottayam", state: "Kerala", district: "Kottayam" },
  { id: "98", name: "Puthuppally", state: "Kerala", district: "Kottayam" },
  { id: "99", name: "Changanassery", state: "Kerala", district: "Kottayam" },
  { id: "100", name: "Kanjirappally", state: "Kerala", district: "Kottayam" },
  { id: "101", name: "Poonjar", state: "Kerala", district: "Kottayam" },
  { id: "102", name: "Aroor", state: "Kerala", district: "Alappuzha" },
  { id: "103", name: "Cherthala", state: "Kerala", district: "Alappuzha" },
  { id: "104", name: "Alappuzha", state: "Kerala", district: "Alappuzha" },
  { id: "105", name: "Ambalappuzha", state: "Kerala", district: "Alappuzha" },
  { id: "106", name: "Kuttanad", state: "Kerala", district: "Alappuzha" },
  { id: "107", name: "Haripad", state: "Kerala", district: "Alappuzha" },
  { id: "108", name: "Kayamkulam", state: "Kerala", district: "Alappuzha" },
  { id: "109", name: "Mavelikkara", state: "Kerala", district: "Alappuzha" },
  { id: "110", name: "Chengannur", state: "Kerala", district: "Alappuzha" },
  { id: "111", name: "Thiruvalla", state: "Kerala", district: "Pathanamthitta" },
  { id: "112", name: "Ranni", state: "Kerala", district: "Pathanamthitta" },
  { id: "113", name: "Aranmula", state: "Kerala", district: "Pathanamthitta" },
  { id: "114", name: "Konni", state: "Kerala", district: "Pathanamthitta" },
  { id: "115", name: "Adoor", state: "Kerala", district: "Pathanamthitta" },
  { id: "116", name: "Karunagappally", state: "Kerala", district: "Kollam" },
  { id: "117", name: "Chavara", state: "Kerala", district: "Kollam" },
  { id: "118", name: "Kunnathur", state: "Kerala", district: "Kollam" },
  { id: "119", name: "Kottarakkara", state: "Kerala", district: "Kollam" },
  { id: "120", name: "Pathanapuram", state: "Kerala", district: "Kollam" },
  { id: "121", name: "Punalur", state: "Kerala", district: "Kollam" },
  { id: "122", name: "Chadayamangalam", state: "Kerala", district: "Kollam" },
  { id: "123", name: "Kundara", state: "Kerala", district: "Kollam" },
  { id: "124", name: "Kollam", state: "Kerala", district: "Kollam" },
  { id: "125", name: "Eravipuram", state: "Kerala", district: "Kollam" },
  { id: "126", name: "Chathannoor", state: "Kerala", district: "Kollam" },
  { id: "127", name: "Varkala", state: "Kerala", district: "Thiruvananthapuram" },
  { id: "128", name: "Attingal", state: "Kerala", district: "Thiruvananthapuram" },
  { id: "129", name: "Chirayinkeezhu", state: "Kerala", district: "Thiruvananthapuram" },
  { id: "130", name: "Nedumangad", state: "Kerala", district: "Thiruvananthapuram" },
  { id: "131", name: "Vamanapuram", state: "Kerala", district: "Thiruvananthapuram" },
  { id: "132", name: "Kazhakkoottam", state: "Kerala", district: "Thiruvananthapuram" },
  { id: "133", name: "Vattiyoorkavu", state: "Kerala", district: "Thiruvananthapuram" },
  { id: "134", name: "Thiruvananthapuram", state: "Kerala", district: "Thiruvananthapuram" },
  { id: "135", name: "Nemom", state: "Kerala", district: "Thiruvananthapuram" },
  { id: "136", name: "Aruvikkara", state: "Kerala", district: "Thiruvananthapuram" },
  { id: "137", name: "Parassala", state: "Kerala", district: "Thiruvananthapuram" },
  { id: "138", name: "Kattakkada", state: "Kerala", district: "Thiruvananthapuram" },
  { id: "139", name: "Kovalam", state: "Kerala", district: "Thiruvananthapuram" },
  { id: "140", name: "Neyyattinkara", state: "Kerala", district: "Thiruvananthapuram" }
];

export const STATES = [
  "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa", 
  "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", "Kerala", 
  "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", 
  "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", 
  "Uttar Pradesh", "Uttarakhand", "West Bengal", "Andaman and Nicobar Islands", 
  "Chandigarh", "Dadra and Nagar Haveli and Daman and Diu", "Lakshadweep", 
  "Delhi (NCT)", "Puducherry", "Jammu and Kashmir", "Ladakh"
].sort();

export const DISTRICTS = Array.from(new Set(CONSTITUENCIES.map(c => c.district)));

export const PARTIES = [
  { id: "LDF", name: "Left Democratic Front", color: "#ef4444", symbol: "/symbols/cpim.png" },
  { id: "UDF", name: "United Democratic Front", color: "#3b82f6", symbol: "/symbols/inc.svg" },
  { id: "NDA", name: "National Democratic Alliance", color: "#f97316", symbol: "/symbols/bjp.svg" },
  { id: "OTH", name: "Others", color: "#6b7280", symbol: "/symbols/inl.png" }
];
